// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDabRXezoxgehh0D2NfPx8UsN6NWZPzfjg',
    appId: '1:281080199117:web:250515c96e3c703e77b684',
    messagingSenderId: '281080199117',
    projectId: 'my-ecommerce-app-4c2b7',
    authDomain: 'my-ecommerce-app-4c2b7.firebaseapp.com',
    storageBucket: 'my-ecommerce-app-4c2b7.firebasestorage.app',
    measurementId: 'G-207KNDF37B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr496VOk8s48Zc6HWtE2o09SyiGt1Mfks',
    appId: '1:281080199117:android:dbe0537b6dc0701277b684',
    messagingSenderId: '281080199117',
    projectId: 'my-ecommerce-app-4c2b7',
    storageBucket: 'my-ecommerce-app-4c2b7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUxWN6eTk-K2TSk9BuSZ1TR826m9eQJAk',
    appId: '1:281080199117:ios:dedf4356845cf3cb77b684',
    messagingSenderId: '281080199117',
    projectId: 'my-ecommerce-app-4c2b7',
    storageBucket: 'my-ecommerce-app-4c2b7.firebasestorage.app',
    iosBundleId: 'com.example.myEcommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUxWN6eTk-K2TSk9BuSZ1TR826m9eQJAk',
    appId: '1:281080199117:ios:dedf4356845cf3cb77b684',
    messagingSenderId: '281080199117',
    projectId: 'my-ecommerce-app-4c2b7',
    storageBucket: 'my-ecommerce-app-4c2b7.firebasestorage.app',
    iosBundleId: 'com.example.myEcommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDabRXezoxgehh0D2NfPx8UsN6NWZPzfjg',
    appId: '1:281080199117:web:8b29a09e7423c5c177b684',
    messagingSenderId: '281080199117',
    projectId: 'my-ecommerce-app-4c2b7',
    authDomain: 'my-ecommerce-app-4c2b7.firebaseapp.com',
    storageBucket: 'my-ecommerce-app-4c2b7.firebasestorage.app',
    measurementId: 'G-8WHJDRD3SW',
  );
}
